# pytorch basics

## check for GPU connectivity

In [1]:
import torch

In [2]:
torch.__version__

'2.4.0'

In [3]:
torch.cuda.is_available()

True

In [7]:
torch.cuda.current_device()

0

In [9]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [11]:
torch.cuda.memory_allocated()

0

# 		○ Tensors basics 
			- A tensor is a generalization of vectos and matrices and is easily understood as a multidimensional array.
			- Term and set of techniques known in ML in traning and operation of deep learning models can be described in terms of tensors. 
			- In many cases tensors are used as repalcement for numpy to use power of GPUs
			- Tensors:- data structure used in linear algebra 
				□ Vectors 
				□ Matrics 
				□ Perform arithmatic operations with tensors
		


In [27]:
import numpy as np

In [29]:
list=[3,4,5,6]
array=np.array(list)

In [31]:
array.dtype

dtype('int32')

# convert numpy to pytorch tensors

In [84]:
tensors=torch.from_numpy(array).cuda()

In [85]:
tensors

tensor([  3,   4, 100,   6], device='cuda:0', dtype=torch.int32)

In [88]:
tensors[:2]

tensor([3, 4], device='cuda:0', dtype=torch.int32)

## change in tensor address also changes the list

In [91]:
tensors[2]=100

In [93]:
tensors

tensor([  3,   4, 100,   6], device='cuda:0', dtype=torch.int32)

In [95]:
array

array([  3,   4, 100,   6])

In [107]:
# to avoid the above issue
tensor1=torch.tensor(array).cuda()

In [109]:
tensor1[1]=20

In [113]:
tensor1, array

(tensor([  3,  20, 100,   6], device='cuda:0', dtype=torch.int32),
 array([  3,   4, 100,   6]))

In [117]:
# create zero's array
# create 1's array
# operations are very simmilar to numpy 

zero_tensor=torch.zeros(2,3,dtype=torch.float64)
one_tensor=torch.ones(2,3,dtype=torch.float64)
zero_tensor, one_tensor

(tensor([[0., 0., 0.],
         [0., 0., 0.]], dtype=torch.float64),
 tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64))

# Arithmetic operations

In [128]:
zero_tensor+2*one_tensor

tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

## 2d array

In [238]:
a=torch.tensor(np.arange(0,15).reshape(5,3)).cuda()
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], device='cuda:0', dtype=torch.int32)

In [240]:
b=torch.tensor(np.arange(30,45).reshape(5,3)).cuda()
b

tensor([[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]], device='cuda:0', dtype=torch.int32)

In [156]:
c=a*b
c

tensor([[  0,  31,  64],
        [ 99, 136, 175],
        [216, 259, 304],
        [351, 400, 451],
        [504, 559, 616]], device='cuda:0', dtype=torch.int32)

In [158]:
c[0,:]

tensor([ 0, 31, 64], device='cuda:0', dtype=torch.int32)

In [160]:
a+b

tensor([[30, 32, 34],
        [36, 38, 40],
        [42, 44, 46],
        [48, 50, 52],
        [54, 56, 58]], device='cuda:0', dtype=torch.int32)

In [170]:
zeros=torch.zeros(5,3,dtype=torch.float64)

In [182]:
torch.add(a,b).sum()

tensor(660, device='cuda:0')

## Dot products and numtiplication operations

In [190]:
a.mul(b)

tensor([[  0,  31,  64],
        [ 99, 136, 175],
        [216, 259, 304],
        [351, 400, 451],
        [504, 559, 616]], device='cuda:0', dtype=torch.int32)

In [233]:
a=torch.tensor(np.arange(5,10,dtype=np.float64)).cuda()
b=torch.tensor(np.arange(0,5,dtype=np.float64)).cuda()
a, b, a.dot(b)

(tensor([5., 6., 7., 8., 9.], device='cuda:0', dtype=torch.float64),
 tensor([0., 1., 2., 3., 4.], device='cuda:0', dtype=torch.float64),
 tensor(80., device='cuda:0', dtype=torch.float64))

## matrix multiplication

In [254]:
a=torch.tensor(np.arange(0,9, dtype=np.float64).reshape(3,3)).cuda()

b=torch.tensor(np.arange(9,18,  dtype=np.float64).reshape(3,3)).cuda()
a,b

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]], device='cuda:0', dtype=torch.float64),
 tensor([[ 9., 10., 11.],
         [12., 13., 14.],
         [15., 16., 17.]], device='cuda:0', dtype=torch.float64))

In [256]:
torch.matmul(a,b)

tensor([[ 42.,  45.,  48.],
        [150., 162., 174.],
        [258., 279., 300.]], device='cuda:0', dtype=torch.float64)

In [258]:
torch.mm(a,b)

tensor([[ 42.,  45.,  48.],
        [150., 162., 174.],
        [258., 279., 300.]], device='cuda:0', dtype=torch.float64)

In [260]:
a@b

tensor([[ 42.,  45.,  48.],
        [150., 162., 174.],
        [258., 279., 300.]], device='cuda:0', dtype=torch.float64)