In [3]:
import torch
from torch.utils.data import Dataset
torch.manual_seed(1)

In [41]:
class toy_set(Dataset):

    def __init__(self,length=100,transform=None):
        self.len=length
        self.x=2* torch.ones(length,2)
        self.y=torch.ones(length,1)
        self.transform=transform

    def __getitem__(self,index):
        sample=self.x[index], self.y[index]
        if self.transform:
            sample=self.transform(sample)
        return sample
    def __len__(self):
        return self.len

In [51]:
our_dataset=toy_set()
our_dataset[1:5], len(our_dataset)

((tensor([[2., 2.],
          [2., 2.],
          [2., 2.],
          [2., 2.]]),
  tensor([[1.],
          [1.],
          [1.],
          [1.]])),
 100)

In [53]:
for i in range(3):
    x, y=our_dataset[i]
    print("index: ", i, '; x:', x, '; y:', y)

index:  0 ; x: tensor([2., 2.]) ; y: tensor([1.])
index:  1 ; x: tensor([2., 2.]) ; y: tensor([1.])
index:  2 ; x: tensor([2., 2.]) ; y: tensor([1.])


In [55]:
for i,j in our_dataset:
    print(i,j)

tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2.

In [65]:
toy_dataset=toy_set(50)
for i,j in toy_dataset:
    print(i,j)

tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2., 2.]) tensor([1.])
tensor([2.

# transforms

In [74]:
class add_mult(object):
    def __init__(self,addx=1,muly=2):
        self.addx=addx
        self.muly=muly

    def __call__(self, sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        sample=x,y
        return sample

In [76]:
a_m=add_mult()
data_set=toy_set()

In [78]:
for i in range(10):
    x, y = data_set[i]
    print('Index: ', i, 'Original x: ', x, 'Original y: ', y)
    x_, y_ = a_m(data_set[i])
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)

Index:  0 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  0 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  1 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  1 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  2 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  2 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  3 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  3 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  4 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  4 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  5 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  5 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:  6 Original x:  tensor([2., 2.]) Original y:  tensor([1.])
Index:  6 Transformed x_: tensor([2., 2.]) Transformed y_: tensor([6., 6.])
Index:

In [94]:
class my_add_mult(object):
    def __init__(self,addx=2,multx=2):
        self.addx=addx
        self.multx=multx

    def __call__(self, sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.multx
        sample=x,y
        return sample

In [96]:
my_data=toy_set(transform=my_add_mult())
for i in range(3):
    x_, y_ = my_data[i]
    print('Index: ', i, 'Transformed x_:', x_, 'Transformed y_:', y_)
    

Index:  0 Transformed x_: tensor([4., 4.]) Transformed y_: tensor([2.])
Index:  1 Transformed x_: tensor([4., 4.]) Transformed y_: tensor([2.])
Index:  2 Transformed x_: tensor([4., 4.]) Transformed y_: tensor([2.])


# compose 

In [105]:
from torchvision import transforms

In [107]:
class mult(object):
    def __init__(self,mult=100):
        self.mult=mult
    def __call__(self,sample):
        x=sample[0]
        y=sample[1]
        x=x*self.mult
        y=y*self.mult
        sample=x,y
        return sample

In [109]:
# combine the trnasofrm
data_transform=transforms.Compose([add_mult(),mult()])
data_transform

Compose(
)

In [121]:
data_set[0], data_transform(data_set[0])

((tensor([2., 2.]), tensor([1.])),
 (tensor([200., 200.]), tensor([600., 600.])))